/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RipRouteImport } from './routes/rip'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminIngestRouteImport } from './routes/admin.ingest'
import { Route as AdminBooksRouteImport } from './routes/admin.books'
import { Route as AdminPacksIndexRouteImport } from './routes/admin.packs.index'
import { Route as AdminPacksSlugRouteImport } from './routes/admin.packs.$slug'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RipRoute = RipRouteImport.update({
  id: '/rip',
  path: '/rip',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIngestRoute = AdminIngestRouteImport.update({
  id: '/admin/ingest',
  path: '/admin/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/admin/books',
  path: '/admin/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPacksIndexRoute = AdminPacksIndexRouteImport.update({
  id: '/admin/packs/',
  path: '/admin/packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPacksSlugRoute = AdminPacksSlugRouteImport.update({
  id: '/admin/packs/$slug',
  path: '/admin/packs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/rip': typeof RipRoute
  '/sign-in': typeof SignInRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/packs/$slug': typeof AdminPacksSlugRoute
  '/admin/packs/': typeof AdminPacksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/rip': typeof RipRoute
  '/sign-in': typeof SignInRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin': typeof AdminIndexRoute
  '/admin/packs/$slug': typeof AdminPacksSlugRoute
  '/admin/packs': typeof AdminPacksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/rip': typeof RipRoute
  '/sign-in': typeof SignInRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/packs/$slug': typeof AdminPacksSlugRoute
  '/admin/packs/': typeof AdminPacksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/rip'
    | '/sign-in'
    | '/admin/books'
    | '/admin/ingest'
    | '/admin/'
    | '/admin/packs/$slug'
    | '/admin/packs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/rip'
    | '/sign-in'
    | '/admin/books'
    | '/admin/ingest'
    | '/admin'
    | '/admin/packs/$slug'
    | '/admin/packs'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/rip'
    | '/sign-in'
    | '/admin/books'
    | '/admin/ingest'
    | '/admin/'
    | '/admin/packs/$slug'
    | '/admin/packs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  RipRoute: typeof RipRoute
  SignInRoute: typeof SignInRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminIngestRoute: typeof AdminIngestRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPacksSlugRoute: typeof AdminPacksSlugRoute
  AdminPacksIndexRoute: typeof AdminPacksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rip': {
      id: '/rip'
      path: '/rip'
      fullPath: '/rip'
      preLoaderRoute: typeof RipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ingest': {
      id: '/admin/ingest'
      path: '/admin/ingest'
      fullPath: '/admin/ingest'
      preLoaderRoute: typeof AdminIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packs/': {
      id: '/admin/packs/'
      path: '/admin/packs'
      fullPath: '/admin/packs/'
      preLoaderRoute: typeof AdminPacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packs/$slug': {
      id: '/admin/packs/$slug'
      path: '/admin/packs/$slug'
      fullPath: '/admin/packs/$slug'
      preLoaderRoute: typeof AdminPacksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  RipRoute: RipRoute,
  SignInRoute: SignInRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminIngestRoute: AdminIngestRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPacksSlugRoute: AdminPacksSlugRoute,
  AdminPacksIndexRoute: AdminPacksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
