/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RipRouteImport } from './routes/rip'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RipIndexRouteImport } from './routes/rip.index'
import { Route as PacksIndexRouteImport } from './routes/packs.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RipSlugRouteImport } from './routes/rip.$slug'
import { Route as PacksNewRouteImport } from './routes/packs.new'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as AdminIngestRouteImport } from './routes/admin.ingest'
import { Route as AdminBooksRouteImport } from './routes/admin.books'
import { Route as UUsernameIndexRouteImport } from './routes/u.$username.index'
import { Route as AdminPacksIndexRouteImport } from './routes/admin.packs.index'
import { Route as UUsernameSlugRouteImport } from './routes/u.$username.$slug'
import { Route as PacksIdEditRouteImport } from './routes/packs.$id.edit'
import { Route as AdminPacksSlugRouteImport } from './routes/admin.packs.$slug'
import { Route as RipUUsernameSlugRouteImport } from './routes/rip.u.$username.$slug'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RipRoute = RipRouteImport.update({
  id: '/rip',
  path: '/rip',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RipIndexRoute = RipIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RipRoute,
} as any)
const PacksIndexRoute = PacksIndexRouteImport.update({
  id: '/packs/',
  path: '/packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RipSlugRoute = RipSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RipRoute,
} as any)
const PacksNewRoute = PacksNewRouteImport.update({
  id: '/packs/new',
  path: '/packs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIngestRoute = AdminIngestRouteImport.update({
  id: '/admin/ingest',
  path: '/admin/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/admin/books',
  path: '/admin/books',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/u/$username/',
  path: '/u/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPacksIndexRoute = AdminPacksIndexRouteImport.update({
  id: '/admin/packs/',
  path: '/admin/packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameSlugRoute = UUsernameSlugRouteImport.update({
  id: '/u/$username/$slug',
  path: '/u/$username/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksIdEditRoute = PacksIdEditRouteImport.update({
  id: '/packs/$id/edit',
  path: '/packs/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPacksSlugRoute = AdminPacksSlugRouteImport.update({
  id: '/admin/packs/$slug',
  path: '/admin/packs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RipUUsernameSlugRoute = RipUUsernameSlugRouteImport.update({
  id: '/u/$username/$slug',
  path: '/u/$username/$slug',
  getParentRoute: () => RipRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/rip': typeof RipRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/book/$id': typeof BookIdRoute
  '/packs/new': typeof PacksNewRoute
  '/rip/$slug': typeof RipSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/packs/': typeof PacksIndexRoute
  '/rip/': typeof RipIndexRoute
  '/admin/packs/$slug': typeof AdminPacksSlugRoute
  '/packs/$id/edit': typeof PacksIdEditRoute
  '/u/$username/$slug': typeof UUsernameSlugRoute
  '/admin/packs/': typeof AdminPacksIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/rip/u/$username/$slug': typeof RipUUsernameSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/sign-in': typeof SignInRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/book/$id': typeof BookIdRoute
  '/packs/new': typeof PacksNewRoute
  '/rip/$slug': typeof RipSlugRoute
  '/admin': typeof AdminIndexRoute
  '/packs': typeof PacksIndexRoute
  '/rip': typeof RipIndexRoute
  '/admin/packs/$slug': typeof AdminPacksSlugRoute
  '/packs/$id/edit': typeof PacksIdEditRoute
  '/u/$username/$slug': typeof UUsernameSlugRoute
  '/admin/packs': typeof AdminPacksIndexRoute
  '/u/$username': typeof UUsernameIndexRoute
  '/rip/u/$username/$slug': typeof RipUUsernameSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collection': typeof CollectionRoute
  '/rip': typeof RipRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/ingest': typeof AdminIngestRoute
  '/book/$id': typeof BookIdRoute
  '/packs/new': typeof PacksNewRoute
  '/rip/$slug': typeof RipSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/packs/': typeof PacksIndexRoute
  '/rip/': typeof RipIndexRoute
  '/admin/packs/$slug': typeof AdminPacksSlugRoute
  '/packs/$id/edit': typeof PacksIdEditRoute
  '/u/$username/$slug': typeof UUsernameSlugRoute
  '/admin/packs/': typeof AdminPacksIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/rip/u/$username/$slug': typeof RipUUsernameSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collection'
    | '/rip'
    | '/sign-in'
    | '/admin/books'
    | '/admin/ingest'
    | '/book/$id'
    | '/packs/new'
    | '/rip/$slug'
    | '/admin/'
    | '/packs/'
    | '/rip/'
    | '/admin/packs/$slug'
    | '/packs/$id/edit'
    | '/u/$username/$slug'
    | '/admin/packs/'
    | '/u/$username/'
    | '/rip/u/$username/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collection'
    | '/sign-in'
    | '/admin/books'
    | '/admin/ingest'
    | '/book/$id'
    | '/packs/new'
    | '/rip/$slug'
    | '/admin'
    | '/packs'
    | '/rip'
    | '/admin/packs/$slug'
    | '/packs/$id/edit'
    | '/u/$username/$slug'
    | '/admin/packs'
    | '/u/$username'
    | '/rip/u/$username/$slug'
  id:
    | '__root__'
    | '/'
    | '/collection'
    | '/rip'
    | '/sign-in'
    | '/admin/books'
    | '/admin/ingest'
    | '/book/$id'
    | '/packs/new'
    | '/rip/$slug'
    | '/admin/'
    | '/packs/'
    | '/rip/'
    | '/admin/packs/$slug'
    | '/packs/$id/edit'
    | '/u/$username/$slug'
    | '/admin/packs/'
    | '/u/$username/'
    | '/rip/u/$username/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionRoute: typeof CollectionRoute
  RipRoute: typeof RipRouteWithChildren
  SignInRoute: typeof SignInRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminIngestRoute: typeof AdminIngestRoute
  BookIdRoute: typeof BookIdRoute
  PacksNewRoute: typeof PacksNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PacksIndexRoute: typeof PacksIndexRoute
  AdminPacksSlugRoute: typeof AdminPacksSlugRoute
  PacksIdEditRoute: typeof PacksIdEditRoute
  UUsernameSlugRoute: typeof UUsernameSlugRoute
  AdminPacksIndexRoute: typeof AdminPacksIndexRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rip': {
      id: '/rip'
      path: '/rip'
      fullPath: '/rip'
      preLoaderRoute: typeof RipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rip/': {
      id: '/rip/'
      path: '/'
      fullPath: '/rip/'
      preLoaderRoute: typeof RipIndexRouteImport
      parentRoute: typeof RipRoute
    }
    '/packs/': {
      id: '/packs/'
      path: '/packs'
      fullPath: '/packs/'
      preLoaderRoute: typeof PacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rip/$slug': {
      id: '/rip/$slug'
      path: '/$slug'
      fullPath: '/rip/$slug'
      preLoaderRoute: typeof RipSlugRouteImport
      parentRoute: typeof RipRoute
    }
    '/packs/new': {
      id: '/packs/new'
      path: '/packs/new'
      fullPath: '/packs/new'
      preLoaderRoute: typeof PacksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ingest': {
      id: '/admin/ingest'
      path: '/admin/ingest'
      fullPath: '/admin/ingest'
      preLoaderRoute: typeof AdminIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/u/$username'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packs/': {
      id: '/admin/packs/'
      path: '/admin/packs'
      fullPath: '/admin/packs/'
      preLoaderRoute: typeof AdminPacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/$slug': {
      id: '/u/$username/$slug'
      path: '/u/$username/$slug'
      fullPath: '/u/$username/$slug'
      preLoaderRoute: typeof UUsernameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/$id/edit': {
      id: '/packs/$id/edit'
      path: '/packs/$id/edit'
      fullPath: '/packs/$id/edit'
      preLoaderRoute: typeof PacksIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packs/$slug': {
      id: '/admin/packs/$slug'
      path: '/admin/packs/$slug'
      fullPath: '/admin/packs/$slug'
      preLoaderRoute: typeof AdminPacksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rip/u/$username/$slug': {
      id: '/rip/u/$username/$slug'
      path: '/u/$username/$slug'
      fullPath: '/rip/u/$username/$slug'
      preLoaderRoute: typeof RipUUsernameSlugRouteImport
      parentRoute: typeof RipRoute
    }
  }
}

interface RipRouteChildren {
  RipSlugRoute: typeof RipSlugRoute
  RipIndexRoute: typeof RipIndexRoute
  RipUUsernameSlugRoute: typeof RipUUsernameSlugRoute
}

const RipRouteChildren: RipRouteChildren = {
  RipSlugRoute: RipSlugRoute,
  RipIndexRoute: RipIndexRoute,
  RipUUsernameSlugRoute: RipUUsernameSlugRoute,
}

const RipRouteWithChildren = RipRoute._addFileChildren(RipRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionRoute: CollectionRoute,
  RipRoute: RipRouteWithChildren,
  SignInRoute: SignInRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminIngestRoute: AdminIngestRoute,
  BookIdRoute: BookIdRoute,
  PacksNewRoute: PacksNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  PacksIndexRoute: PacksIndexRoute,
  AdminPacksSlugRoute: AdminPacksSlugRoute,
  PacksIdEditRoute: PacksIdEditRoute,
  UUsernameSlugRoute: UUsernameSlugRoute,
  AdminPacksIndexRoute: AdminPacksIndexRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
